// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'test': string;
  'test2': string;
  'test3': string;
}
declare var cssExports: CssExports;
export = cssExports;
